apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: oficina
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DB_HOST: "sqlserver"
  DB_PORT: "1433"
  DB_NAME: "AutoRepairShopDb"
  LOG_LEVEL: "Information"
