apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: oficina # Cria um Deployment chamado api dentro do namespace oficina.
spec:
  replicas: 1 # Garante que sempre exista 1 Pod rodando dessa aplicação.
  selector:
    matchLabels:
      app: api # Deployment gerencia todos os Pods que tiverem o label app=api
  template:
    metadata:
      labels:
        app: api # Cada Pod criado terá o label app=api
    spec:
      imagePullSecrets:
        - name: ghcr-secret # Kubernetes deve usar o Secret ghcr-secret para autenticar no GitHub Container Registry (GHCR) ao baixar a imagem privada
      containers:
        - name: api # Define um container chamado api dentro do Pod
          image: ghcr.io/autorepairorg/autorepairshop-api:latest # Imagem padrão, será atualizada pelo CD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"  # O Kubernetes reserva no mínimo: 0.1 CPU e 128 MB RAM
            limits:
              cpu: "500m"
              memory: "256Mi" # Container não deve ultrapassar 0.5 CPU 256 MB RAM
          imagePullPolicy: Always # Sempre tenta baixar novamente, mesmo que já exista
          ports:
            - containerPort: 8080 # Porta a ser utilizada por services e probes
          envFrom: # Injeção de todas as chaves desses recursos como variáveis de ambiente no container
            - configMapRef:
                name: api-config
            - secretRef:
                name: sqlserver-secret
            - secretRef:
                name: api-secrets
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            # Datadog APM
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "autorepairshop-api"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"      
