apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: oficina
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DB_HOST: "autorepair-sqlserver.cflewrgiz7x4.us-east-1.rds.amazonaws.com"
  DB_PORT: "1433"
  DB_NAME: "AutoRepairShop"
  DB_USER: "admin"
  LOG_LEVEL: "Information"
  ConnectionStrings__DefaultConnection: "Server=autorepair-sqlserver.cflewrgiz7x4.us-east-1.rds.amazonaws.com,1433;Database=AutoRepairShop;User Id=admin;Password=AutoRepair2024!;TrustServerCertificate=True;"
