spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api
          image: ghcr.io/autorepairorg/autorepairshop-api:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: sqlserver-secret
            - secretRef:
                name: api-secrets
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "autorepairshop-api"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
