apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: oficina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: datadog-init
          image: gcr.io/datadoghq/dd-lib-dotnet-init:latest
          command: ["sh", "copy-lib.sh"]
          env:
            - name: DD_DOTNET_TRACER_HOME
              value: /datadog-lib
          volumeMounts:
            - name: datadog-lib
              mountPath: /datadog-lib
      containers:
        - name: api
          image: ghcr.io/autorepairorg/autorepairshop-api:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: sqlserver-secret
            - secretRef:
                name: api-secrets
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            # Datadog APM
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "autorepairshop-api"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            # Datadog .NET Profiler
            - name: CORECLR_ENABLE_PROFILING
              value: "1"
            - name: CORECLR_PROFILER
              value: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
            - name: CORECLR_PROFILER_PATH
              value: /datadog-lib/Datadog.Trace.ClrProfiler.Native.so
            - name: DD_DOTNET_TRACER_HOME
              value: /datadog-lib
          volumeMounts:
            - name: datadog-lib
              mountPath: /datadog-lib
      volumes:
        - name: datadog-lib
          emptyDir: {}
