apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: datadog
  labels:
    app: datadog-agent
    app.kubernetes.io/name: datadog-agent
    app.kubernetes.io/part-of: autorepairshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent
  labels:
    app: datadog-agent
    app.kubernetes.io/name: datadog-agent
    app.kubernetes.io/part-of: autorepairshop
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - endpoints
      - events
      - services
      - pods
      - pods/log
      - componentstatuses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list"]
  - nonResourceURLs:
      - "/metrics"
      - "/metrics/cadvisor"
      - "/version"
      - "/healthz"
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent
  labels:
    app: datadog-agent
    app.kubernetes.io/name: datadog-agent
    app.kubernetes.io/part-of: autorepairshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
  - kind: ServiceAccount
    name: datadog-agent
    namespace: datadog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-cluster-agent
  namespace: datadog
  labels:
    app: datadog-cluster-agent
    app.kubernetes.io/name: datadog-cluster-agent
    app.kubernetes.io/part-of: autorepairshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-cluster-agent
  labels:
    app: datadog-cluster-agent
    app.kubernetes.io/name: datadog-cluster-agent
    app.kubernetes.io/part-of: autorepairshop
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - endpoints
      - events
      - services
      - pods
      - componentstatuses
      - configmaps
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - datadogtoken
      - datadog-leader-election
      - datadog-cluster-id
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - "/version"
      - "/healthz"
      - "/metrics"
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-cluster-agent
  labels:
    app: datadog-cluster-agent
    app.kubernetes.io/name: datadog-cluster-agent
    app.kubernetes.io/part-of: autorepairshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-cluster-agent
subjects:
  - kind: ServiceAccount
    name: datadog-cluster-agent
    namespace: datadog
