apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
  labels:
    k8s-app: fluent-bit
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/part-of: autorepairshop
data:
  cluster.name: autorepairshop-eks
  logs.region: us-east-1
  http.server: "On"
  http.port: "2020"
  read.head: "Off"
  read.tail: "On"
